# Generated by Django 2.1.2 on 2018-10-31 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_auto_20181031_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, blank=True,null=True,),
            preserve_default=False,
        ),
    ]
