# Generated by Django 2.1.2 on 2018-10-31 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_good_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='owner',
            field=models.ForeignKey(default=9999, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
