# Generated by Django 2.1.2 on 2018-11-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_photo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='category',
            field=models.IntegerField(choices=[(0, '家具'), (1, 'エビペン'), (2, 'OTHER')], default=0, verbose_name='カテゴリ'),
        ),
    ]
