# Generated by Django 2.1.2 on 2018-11-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_photo_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='photo_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='photo',
            name='relese',
            field=models.IntegerField(default=0),
        ),
    ]
