# Generated by Django 2.1.2 on 2018-11-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20181114_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='写真'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='is_dispalyed',
            field=models.BooleanField(default=False, verbose_name='表示させますか？'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='表示用として使う'),
        ),
    ]
